# Generated by Django 4.2.2 on 2025-07-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
    ]
