# Generated by Django 4.2.2 on 2025-07-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_date'),
        ('users', '0005_alter_payment_date'),
    ]

    operations = [
    ]
