# Generated by Django 4.2.2 on 2025-07-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(help_text='Добавьте ссылку на урок', verbose_name='Ссылка на урок'),
        ),
    ]
