# Generated by Django 5.2.5 on 2025-08-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_lesson_owner_alter_lesson_video_link_and_more'),
        ('lms', '0003_alter_lesson_video_link'),
    ]

    operations = [
    ]
